name: Build and deploy on k3d and cdk8s

on:
  pull_request:
  push:

jobs:
  cdk8s-k3d:
    name:  CDK8s with k3d
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: AbsaOSS/k3d-action@v1.3.1
        name: "Create k3d Cluster"
        id: test-cluster-1
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 1
            --config=k3d.yaml
      
      - name: Cluster info
        run: |
          echo test-cluster-1: ${{ steps.test-cluster-1.outputs.network }} ${{ steps.test-cluster-1.outputs.subnet-CIDR }}
          echo
          kubectl cluster-info --context k3d-test-cluster-1

      - name: Install python dependencies
        run: |
          pip3 install pipenv
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
          pipenv install
      
      - name: Install CDK8s-cli
        run: npm install -g cdk8s-cli

      - name: CDK8s synth
        run: |
          cdk8s synth

      - name: Get svc and pods
        run: |
          kubectl apply -f ./dist/hello.k8s.yaml
          kubectl get services,pods -o wide
