name: Build and Deploy to k3d with cdk8s

on:
  pull_request:
  push:

jobs:
  cdk8s-k3d:
    name:  Define Kubernetes application with CDK8s and run on k3d
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1          

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - uses: AbsaOSS/k3d-action@v1.3.1
        name: "Create k3d Cluster"
        id: test-cluster-1
        with:
          cluster-name: "test-cluster-1"
          args: >-
            --agents 1
            --config=k3d.yaml

      - name: Cluster info
        run: |
          echo test-cluster-1: ${{ steps.test-cluster-1.outputs.network }} ${{ steps.test-cluster-1.outputs.subnet-CIDR }}
          echo
          kubectl cluster-info --context k3d-test-cluster-1

      - name: Get nodes
        run: |
          kubectl get nodes -o wide

      - name: Install cdk8s
        run: npm install -g cdk8s-cli

      - name: CDK8s deploy
        run: |
          cdk8s synth
          kubectl apply -f ./dist/hello.k8s.yaml

      - name: Get svc and pods
        run: |
          kubectl get services,pods -o wide
